Fix Error: ECONRESET
Due to some issues with OpenSSl/TLS, connections to sharepoint sometimes endup in:

Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)

Issue also described here: https://github.com/joyent/node/issues/5360